name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Ali Docker
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Multi-arch Docker Nginx Image
        id: docker_build_nginx
        uses: docker/build-push-action@v2
        with:
          context: proxy
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/goodrain/proxy-pass:latest
            registry.cn-hangzhou.aliyuncs.com/goodrain/proxy-pass:v${{ github.run_number }}

      - name: Build and Push Multi-arch Docker NodeJob Image
        id: docker_build_nodeJob
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-hangzhou.aliyuncs.com/goodrain/node-job:latest
            registry.cn-hangzhou.aliyuncs.com/goodrain/node-job:v${{ github.run_number }}

